Feature/nav categories
Miguelslo27/ecommerce-php-reborn pull request #122
Opened 2020-05-21 18:49 UTC by fdsosa

Resolved #119

2020-05-27 21:54 UTC, Miguelslo27 requested changes
For some reason, when you **get into** a **category** page and see articles, the **sidebar** with all the other **categories is missing**. We should get the sidebar back to have a more comfortable navigation

2020-05-27 21:54 UTC, Miguelslo27 commented on template_dev/components/footer/footer.php
> +              for($i = 0; $i < 3; $i++) {
We should keep all categories here, as in the header navigation (I know, it breaks the layout in the footer, we can record a bug later)

2020-05-27 21:54 UTC, Miguelslo27 commented on template_dev/components/footer/footer.php
> +          <?php endif ?>
Remove this `else` so if there are no categories, the user will see nothing, we should use that check to change the parent link of the dropdown, so if the dropdown has no items, should not be a dropdown at all. Make sense?

2020-05-27 21:54 UTC, Miguelslo27 commented on template_dev/components/header/header.php
> +            <?php endif ?>
The same thing that the previous comment, in the footer we should not show a message if there are no categories, instead we should not show anything

2020-05-27 21:54 UTC, Miguelslo27 commented on template_dev/pages/category.php
> +    $categories            = getCategories();
Let's match the spaces between the variable and before the `=` sign

2020-05-28 18:04 UTC, fdsosa commented
> For some reason, when you **get into** a **category** page and see articles, the **sidebar** with all the other **categories is missing**. We should get the sidebar back to have a more comfortable navigation

El **sidebar** estaba dentro de una condicional donde había una variable que estaba definida en **articles**, la variable llama a la **categoria** con **id 0**, la cual no exisite por eso no se desplegaba el **sidebar**.

2020-05-28 20:17 UTC, Miguelslo27 approved these changes

2020-05-28 20:18 UTC, merged