Feature/article details
Miguelslo27/ecommerce-php-reborn pull request #128
Opened 2020-06-08 16:27 UTC by fdsosa

Resolve #124

2020-06-08 22:00 UTC, Miguelslo27 requested changes
Some change requests, some doubts to ask, nothing big

2020-06-08 22:00 UTC, Miguelslo27 commented on core/api.php
>    $status       = addToCart($request->qty);
Keep spaces at a minimum

2020-06-08 22:00 UTC, Miguelslo27 commented on core/api/cart.php
> +  if((getRequestData('qty')) > 0){
Is there a reason to wrap the `getRequestData(...)` inside parentheses?

2020-06-08 22:00 UTC, Miguelslo27 commented on core/api/cart.php
> +    $qty    = getRequestData('qty');
Minimum spaces

2020-06-08 22:00 UTC, Miguelslo27 commented on core/api/cart.php
> +  */
Is this still giving an error or we can remove the comments at all? Just asking :)

2020-06-08 22:00 UTC, Miguelslo27 commented on template_dev/css/layout.css
> +  scroll-behavior: smooth;
Nice 👌

2020-06-09 01:58 UTC, fdsosa commented on core/api/cart.php
> +  */
The variable `$qty` is a **string**, function `addToCart_checkIncommingData` test if `$qty` is a **integer** or **double**. We hace 3 options, change the type of `$qty`, modify the function or delete the test of  `$qty`

2020-06-09 12:12 UTC, Miguelslo27 approved these changes
Excelent work! 💪 Keep doing this

2020-06-09 12:14 UTC, Miguelslo27 commented on core/api/cart.php
> +  */
Let's transform the qty to `integer` before the check, see `intval` native PHP function

2020-06-09 13:14 UTC, merged