Feature/search results
Miguelslo27/ecommerce-php-reborn pull request #130
Opened 2020-06-12 21:37 UTC by fdsosa

Resolve #129

2020-06-15 16:08 UTC, Miguelslo27 requested changes

2020-06-15 16:08 UTC, Miguelslo27 commented on core/core.php
> +  }
This block isn't used at all, in fact the function `search` is not defined. Could you check how are you performing the search and clean this up?

2020-06-15 16:08 UTC, Miguelslo27 commented on core/api/helpers.php
> +  }
For some reason, when you paginate the search result, the search stops working, my guess is something on this logic, could you check it out?

2020-06-16 18:01 UTC, fdsosa commented on core/api/helpers.php
> +  }
I try it, but the search doesnt stops working.

2020-06-18 14:58 UTC, merged