feature/admin-category-form-improve - Improved form
Miguelslo27/ecommerce-php-reborn pull request #204
Opened 2020-11-20 15:31 UTC by fdsosa

Two doubts:

-  I do not know if the buttons colors of the create form are the most appropriate.
- Should we keep the icons on both buttons?

2020-11-21 14:06 UTC, Miguelslo27 commented
About the colors, I think is ok for this stage of the project, after we have the admin complete, we will start improving design aspects of the entire platform.

The icons are ok also, we can think in a better icon for the _Save and create other_, but by now it works 👌

2020-11-21 17:06 UTC, Miguelslo27 requested changes

2020-11-21 17:06 UTC, Miguelslo27 commented on admin/templates/components/admin.js
> +const categoryButtonSecondary = document.getElementById('category-button-secondary');
Let's set a more descriptive name to the secondary button, in this case the button is `saveAndCreateNew` or alike

2020-11-21 17:06 UTC, Miguelslo27 commented on admin/templates/components/admin.js
> +  document.getElementById('category_parent').value = 'no-category';
Isn't the `reset()` the same as cleaning manually? We are doing both for some reason?

2020-11-21 17:06 UTC, Miguelslo27 commented on admin/templates/components/categories.php
> +          <button class="button button-secondary" data-success="<?php bind(!empty(getSession('request_messages')) ? getSession('request_messages')->succeeded : "")?>" id="category-button-secondary" t
Same here for the id of the button

2020-11-23 14:50 UTC, fdsosa commented on admin/templates/components/admin.js
> +  document.getElementById('category_parent').value = 'no-category';
The reset method **didnt empty the inputs** for some reason, I think is because we load the inputs value with the function `getPreformData()`, so I put a **conditional** to load the inputs value. Now works fine without that JS code.

2020-11-24 13:44 UTC, Miguelslo27 commented on admin/templates/components/admin.js
> +  document.getElementById('category_parent').value = 'no-category';
Make sense then, thanks 👌

2020-11-24 13:57 UTC, Miguelslo27 approved these changes

2020-11-24 13:57 UTC, merged