Feature/contact page
Miguelslo27/ecommerce-php-reborn pull request #98
Opened 2020-03-23 03:13 UTC by fdsosa

Resolved #43

2020-03-30 16:19 UTC, Miguelslo27 requested changes
En general está impecable el PR, sólo algunos cambios.
También bajé los cambios y ví la pantalla de contacto, sobre eso lo que me gustaría es que los formularios se parezcan más a lo que habías hecho antes.

Cuando te pedí que fusionaras lo que había antes con lo que habías hecho vos, quería que mantuvieras la línea de diseño que estabas siguiendo, que me gustó mucho más que la que yo tenía :)

2020-03-30 16:19 UTC, Miguelslo27 commented on template_dev/components/contact-content/contact-content.css
> +  max-width: 1600px;
El `max-width: 1600px` de la clase `contact-section` choca con el `max-width: 1200px` de la clase inner del layout.

Tiene un motivo agrandar el máximo en este contexto? Si lo tiene lo dejamos :)

2020-03-30 16:19 UTC, Miguelslo27 commented on template_dev/components/contact-content/contact-content.css
> +  min-height: 40vh;
Este `min-height: 40vh` no lo entiendo 😆 En que momento podría reducirse tanto el alto como para ponérle un mínimo?

2020-03-30 16:19 UTC, Miguelslo27 commented on template_dev/pages/contact.php
> +  'page' => 'articles',
El parámetro `'page'` es para identificar el documento, debería tener un nombre acorde, como `contact`

2020-03-31 20:21 UTC, fdsosa commented on template_dev/components/contact-content/contact-content.css
> +  min-height: 40vh;
Jaja ya lo cambio, no se por que lo puse la verdad

2020-04-01 20:27 UTC, Miguelslo27 approved these changes

2020-04-01 20:27 UTC, merged